language: node_js
node_js:
- '0.10'
env:
  global:
  - GIT_COMMITTER_NAME="Yuta OHWATARI"
  - GIT_COMMITTER_EMAIL="yyutao88@gmail.com"
  - GIT_AUTHOR_NAME="Yuta OHWATARI"
  - GIT_AUTHOR_EMAIL="yyutao88@gmail.com"
  - secure: Yud/BwYFj7AeFYxVlKkoukGMgeDrt07IcOzZZjkx/j2wGnSaZgZChY3f8wJdjDsL4Ia8uN8YmNrwal5DnNJYPh4GgKky2rhjjosnpPBXWeBP/sEaMQNAHMEiX953Wl7avnREbqS2yPO+r0ZaEbhLoQSEftpHyFAZO/evlNWnJa4=
branches:
  only:
    - master
    - develop
before_script:
- npm install -g bower grunt-cli
- bower install
- gem install sass compass
after_success:
- grunt build
- cd dist
- git init || true
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- git remote add heroku git@heroku.com:stickr-staging.git
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- yes | heroku keys:add
- git add -A
- git commit -m "Deployment update" --allow-empty
- yes | git push heroku master
- heroku keys:remove `whoami`@`hostname`
- cd ..
notifications:
  email: false
  hipchat:
    on_success: always
    on_failure: always
    rooms:
      secure: VN9PCqVT7XwFIEemGo2CER3hY3QEdlCspKm1TperNFKt+53Q6c2tu/NxHW2k+qXzk9p1JxI6YG+w2CGUTiodXJ2mt0pFfffwp67fwEGTGw3vTAGmsyWiT3HWeA+1PMEmV08/XpqoEUiVnL4QXhDM3bgOfRCWouIauJM1yBKFKds=
