language: node_js
node_js:
  - '0.10'
env:
  global:
    - GIT_COMMITTER_NAME="Yuta OHWATARI"
    - GIT_COMMITTER_EMAIL="yyutao88@gmail.com"
    - GIT_AUTHOR_NAME="Yuta OHWATARI"
    - GIT_AUTHOR_EMAIL="yyutao88@gmail.com"
    - secure: a5FiP+bLTHkxaKz9qYjRrUcyMZ3U7n/Gckz4uylJgXNdoXhgSIbSyeosfoq5i9E78LfCBSwuUUoWEy7w8QwpJKuWGXmvIN0bKFlsnyjq71dgkbkeUusYy2V7o1lBqnMfENSF7xVLT4WuxQ8m7NvrwGT2iSprhEVHFe2dOrbqG9Y=
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - gem install sass compass
after_success:
  - grunt build
  - sh deploy.sh
notifications:
  email: false
  hipchat:
    on_success: always
    on_failure: always
    rooms:
      secure: VN9PCqVT7XwFIEemGo2CER3hY3QEdlCspKm1TperNFKt+53Q6c2tu/NxHW2k+qXzk9p1JxI6YG+w2CGUTiodXJ2mt0pFfffwp67fwEGTGw3vTAGmsyWiT3HWeA+1PMEmV08/XpqoEUiVnL4QXhDM3bgOfRCWouIauJM1yBKFKds=